version: '3'
services:
  wazuh:
    image: wazuh/wazuh:latest
    ports:
      - "1514:1514/udp"
      - "55000:55000/tcp"
      - "55001:55001/tcp"
      - "55002:55002/tcp"
      - "55003:55003/tcp"
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
